### PR TITLE
Ported fix from 4.x: Changed hardcoded command center path to relative path.

### PR DESCRIPTION
**Pull request by vmaraloiu**

### CODE REVIEW

**Comment by dpwspoon** [comment]
@vmaraloiu Have you checked to make sure this still works in the OOTB case?

**Comment by vmaraloiu** [comment]
@dpwspoon Yes, I have tested by changing the variable (_3eb in general.js) value from "/commandcenter" to "../" in an out of the box version taken from: (http://developer.kaazing.com/downloads/jms-edition-download/) and it works.

Basically it worked because the ROOT_PATH should point to parent folder of js folder, but if we change URI, ROOT_PATH should be changed too. In this case the relative path will work any time.

**Comment by dpwspoon** [comment]
@ahousing do we have a plan on bamboo that release this?  If so can you kick it off please

**Comment by ahousing** [comment]
@dpwspoon: There is a bamboo plan, and I [ran it (green)](http://bamboo.kaazing.wan/browse/JENKINS-KGCONSOLE50-13).  As a side note, it's in the section labelled "Move to Jenkins".  All plans in this section should be rewritten and put on Jenkins.  Let me know if you want to track this in any way.

**Pull request merged**
